### PR TITLE
Add Support for OpenMask wallet #131

### PR DESCRIPTION
**Pull request by KuznetsovNikita**
Basic integration with OpenMask browser extension

### CODE REVIEW

**Comment by KuznetsovNikita** [comment]
The Demo:
https://user-images.githubusercontent.com/22742808/203086436-87ccd108-bfc1-4540-8aeb-3a180ff014cf.mp4

**Comment by shaharyakir** [comment]
Hi, thanks for making this integration! I plan to split it between this repo and https://github.com/ton-defi-org/ton-connection, but it requires some API changes that were coming anyway, so it could take a few days.

**Comment by KuznetsovNikita** [comment]
> Hi, thanks for making this integration! I plan to split it between this repo and https://github.com/ton-defi-org/ton-connection, but it requires some API changes that were coming anyway, so it could take a few days.

Ok, got it.

One more note, It's a basic integration. 

Generally I could create advanced integration:
1) add a `watch asset` button to app to offer to add asset to wallet 
(the example - https://www.openmask.app/docs/advanced/assets)
2) autodetect network and offer wallet to switch to correct one 
(the example - https://www.openmask.app/docs/network)

to completely upgrade user experience.

The rest of wallet don't have such features so it would require a custom provider.

I'm not sure, should I do it or not

**Comment by shaharyakir** [comment]
1. Importing assets to wallet -> other wallets currently auto-import them, based on txn monitoring, so there's no need to manually import
2. network switch -> at the moment we plan to support only mainnet

Preferably the way to go is to add the basic provider to ton-connection (but not yet, because of the API changes mentioned)

**Comment by shaharyakir** [comment]
merged via #157

**Pull request closed without merging**
